### PR TITLE
feat: allow usage as a library

### PR DESCRIPTION
**Pull request by josegonzalez**
- Set the package to something other than "main" so it can be importable
- Removed unnecessary `Service` keyword in struct declaration
- Exposed RequestHandler and BackendConfig
- Added a `RoutePrefix` option to allow mounting the routes at a subpath

Usage with `gin` is as follows:

```go
package main
import (
	"github.com/asim/git-http-backend"
	"github.com/gin-gonic/gin"
)

func main() {
	githttpbackend.BackendConfig.RoutePrefix = "@git/"

	r := gin.New()
	r.NoRoute(gin.WrapF(githttpbackend.RequestHandler()))
	r.Run(":8080")
}
```

### CODE REVIEW

**Comment by asim** [comment]
I'll refactor. I'm a bit annoyed by this change and might just revert.

**Comment by asim** [comment]
@josegonzalez you might as well fork.

**Comment by asim** [comment]
Now refactored out to server package https://github.com/asim/git-http-backend/commit/c3786eebce59f87adbd8647064f99ac4d47e7a62

https://godoc.org/github.com/asim/git-http-backend/server

**Comment by josegonzalez** [comment]
@asim can you take a 0.2.0? Reusing the old tag somehow is making go mod grumpy.

**Comment by asim** [comment]
Done.

**Pull request merged**
